# Generated by Django 4.2.6 on 2023-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Res_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
