# Generated by Django 4.2.6 on 2023-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0002_remove_restaurant_id_alter_restaurant_res_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Res_Phone',
            field=models.CharField(max_length=50),
        ),
    ]
