# Generated by Django 4.2.6 on 2023-10-13 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0003_alter_restaurant_res_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('Cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cate_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.category'),
        ),
    ]
