# Generated by Django 4.2.6 on 2023-10-13 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0004_category_restaurant_cate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('Dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dish_Name', models.CharField(max_length=50)),
                ('Dish_img', models.ImageField(blank=True, default='', null=True, upload_to='dish_img/')),
                ('Dish_Des', models.CharField(max_length=255)),
                ('Dish_Price', models.IntegerField()),
                ('cate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Dish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.dish'),
        ),
    ]
