# Generated by Django 4.2.6 on 2023-10-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0006_contact_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('Web_id', models.AutoField(primary_key=True, serialize=False)),
                ('Web_address', models.CharField(max_length=50)),
                ('Web_email', models.CharField(max_length=50)),
                ('Web_phone', models.CharField(max_length=50)),
                ('Web_facebook_link', models.CharField(max_length=50)),
                ('Web_instagram_link', models.CharField(max_length=50)),
                ('Web_twitter_link', models.CharField(max_length=50)),
                ('Web_whatsapp_link', models.CharField(max_length=50)),
            ],
        ),
    ]
