# Generated by Django 4.2.6 on 2023-10-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0007_websiteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('Ar_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ar_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Ar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.area'),
        ),
    ]
