# Generated by Django 4.2.6 on 2023-10-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0008_area_restaurant_ar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Ar_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Cate_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Res_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
