# Generated by Django 4.2.6 on 2023-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0009_alter_area_ar_name_alter_category_cate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Res_img',
            field=models.FileField(blank=True, default='', null=True, upload_to='Res_img/'),
        ),
    ]
