# Generated by Django 4.2.6 on 2023-11-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0010_restaurant_res_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Dish_id',
        ),
        migrations.AddField(
            model_name='dish',
            name='Res_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.restaurant'),
        ),
    ]
