# Generated by Django 4.2.6 on 2023-11-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0011_remove_restaurant_dish_id_dish_res_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordering_System_app.dish')),
            ],
        ),
    ]
