# Generated by Django 4.2.6 on 2023-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0012_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Dish_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
