# Generated by Django 4.2.6 on 2023-11-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0013_alter_dish_dish_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='dish_name',
            new_name='product',
        ),
    ]
