# Generated by Django 4.2.6 on 2023-11-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0014_rename_dish_name_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='dish_name',
        ),
    ]
