# Generated by Django 4.2.6 on 2023-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0015_rename_product_cartitem_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='Web_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
