# Generated by Django 4.2.6 on 2023-11-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering_System_app', '0017_rename_res_email_restaurant_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='username',
            new_name='Res_Email',
        ),
    ]
